export { default as Navbar } from './Navbar';
export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as Services } from './Services';
export { default as Projects } from './Projects';
export { default as ConnectSection } from './Connect';
export { default as Skillntime } from './Skills';
export { default as Achievements } from './Achivements';
export { default as Footer } from './Footer';
export { default as AboutMe } from './AboutMe';
export { default as Projectss } from './Projectsdesc';
export { default as Contact } from './Contact';
export{default as AchivementsPage} from './AcivementsPage';
export { default as ProfileSection } from './ProfileSection';